// Builds the note editor that runs inside the WebView into a single HTML string:
//   editor-web/index.tsx + index.html  →  src/features/notes/editor/editorHtml.ts
// Run with `npm run editor:build` after changing editor-web/ or src/features/notes/editor/bridges.ts.
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(path.join(root, 'package.json'));
const tentapDir = path.dirname(require.resolve('@10play/tentap-editor/package.json'));
const reactDomDir = path.dirname(require.resolve('react-dom/package.json'));

const redirects = {
  name: 'dozi-editor-redirects',
  setup(b) {
    // TenTap's web side (useTenTap, bridges) from its TypeScript source, so the bundle has one
    // copy of TipTap shared with our own extensions.
    b.onResolve({ filter: /^@10play\/tentap-editor(\/web)?$/ }, () => ({
      path: path.join(tentapDir, 'src/webEditorUtils/index.ts'),
    }));
    // TenTap ships its own React DOM 18; the editor must use the app's React DOM (same as React).
    b.onResolve({ filter: /^react-dom(\/.*)?$/ }, (args) => ({
      path: require.resolve(args.path.replace(/^react-dom/, reactDomDir)),
    }));
  },
};

const result = await build({
  entryPoints: [path.join(root, 'editor-web/index.tsx')],
  bundle: true,
  minify: true,
  write: false,
  format: 'iife',
  jsx: 'automatic',
  target: ['chrome80', 'safari14'],
  define: { 'process.env.NODE_ENV': '"production"' },
  tsconfig: path.join(root, 'editor-web/tsconfig.json'),
  plugins: [redirects],
  // TenTap checks for Expo with a require() that must fail inside the WebView (it does: the
  // module isn't bundled), so it uses its real focus listener there.
  external: ['expo-constants'],
  logLevel: 'warning',
});

const script = result.outputFiles[0].text;
if (script.includes('</script')) throw new Error('The editor script contains "</script"');
const template = readFileSync(path.join(root, 'editor-web/index.html'), 'utf8');
const html = template.replace('/*EDITOR_SCRIPT*/', () => script);

const out = path.join(root, 'src/features/notes/editor/editorHtml.ts');
writeFileSync(
  out,
  '// GENERATED by `npm run editor:build` from editor-web/ — do not edit by hand.\n' +
    `export const editorHtml = ${JSON.stringify(html)};\n`,
);
console.log(`Wrote ${path.relative(root, out)} (${Math.round(html.length / 1024)} KB)`);
